from docx import Document
from docx.shared import Inches
from docx.oxml.ns import qn

def create_test_docx(filename="test_document.docx"):
    """
    Creates a .docx file that will work with your title extraction code.
    The code looks for specific XML patterns in paragraph styles.
    """
    
    doc = Document()
    
    # Add a main title with "Heading" style (will have depth=0)
    main_title = doc.add_paragraph("Main Document Title")
    main_title.style = "Heading 1"  # This creates the XML pattern the code looks for
    
    # Add some content
    doc.add_paragraph("This is the introduction paragraph of the document.")
    
    # Add a subtitle (will have depth=0)
    subtitle = doc.add_paragraph("Document Subtitle")
    subtitle.style = "Subtitle"  # This creates the required XML pattern
    
    # Add more content
    doc.add_paragraph("This is some body text under the subtitle.")
    
    # Create a table of contents section
    # The code specifically looks for "Contents[N]" styles with "__RefHeading___Toc" text
    toc_heading = doc.add_paragraph("Table of Contents")
    toc_heading.style = "Heading 2"
    
    # These would typically be generated by Word's TOC feature
    # The code looks for "__RefHeading___Toc" in the XML and "Contents[N]" style
    toc1 = doc.add_paragraph("Chapter 1: Introduction\t__RefHeading___Toc123456789")
    # Note: You'd need to manually set the style to "Contents1" in Word for this to work
    
    toc2 = doc.add_paragraph("Chapter 2: Main Content\t__RefHeading___Toc987654321") 
    # Note: You'd need to manually set the style to "Contents2" in Word for this to work
    
    # Add the actual chapters
    chapter1 = doc.add_paragraph("Chapter 1: Introduction")
    chapter1.style = "Heading 1"
    
    doc.add_paragraph("This is the content of chapter 1.")
    
    chapter2 = doc.add_paragraph("Chapter 2: Main Content")
    chapter2.style = "Heading 1"
    
    doc.add_paragraph("This is the content of chapter 2.")
    
    # Save the document
    doc.save(filename)
    print(f"Created {filename}")
    return filename

def create_manual_toc_docx(filename="manual_toc_document.docx"):
    """
    Creates a document with manually formatted TOC entries that match
    what your code is looking for more precisely.
    """
    doc = Document()
    
    # Add main title
    main_title = doc.add_paragraph("Document with Manual TOC")
    main_title.style = "Heading 1"
    
    # The code looks for very specific patterns, so let's create them manually
    # Add paragraphs that will have the right XML structure when saved
    
    # Main heading (depth=0)
    heading = doc.add_paragraph("Main Section")
    heading.style = "Heading 1"
    
    doc.add_paragraph("Content under main section.")
    
    # Subheading
    subheading = doc.add_paragraph("Subsection")
    subheading.style = "Heading 2"
    
    doc.add_paragraph("Content under subsection.")
    
    doc.save(filename)
    print(f"Created {filename}")
    return filename

# Create both test files
if __name__ == "__main__":
    create_test_docx()
    create_manual_toc_docx()
    
    print("\nTo make these work perfectly with your code:")
    print("1. Open the generated .docx files in Microsoft Word")
    print("2. For TOC entries to work, you need to:")
    print("   - Insert a proper Table of Contents using Word's Insert > Table of Contents")
    print("   - Or manually format paragraphs with 'Contents1', 'Contents2', etc. styles")
    print("   - Make sure TOC entries contain '__RefHeading___Toc' text")
    print("\nThe generated files will work for basic title extraction with Heading styles.")
